---
- name: Red Hat Repositories
  include_role:
    name: redhat.satellite.repositories
# vars: satellite_products
- name: Content Credentials
  include_role:
    name: redhat.satellite.content_credentials
# vars: satellite_content_credentials
- name: Sync Plans
  include_role:
    name: redhat.satellite.sync_plans
# vars: satellite_sync_plans
- name: Content Views
  include_role:
    name: redhat.satellite.content_views
# vars: satellite_content_views
# content_views requires ansible collection redhat.satellite >= 2.1.0
