---
- name: 'Configure Satellite Settings'
  setting:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: default_redhat_download_policy
      value: immediate
    - name: default_proxy_download_policy
      value: immediate
    - name: rss_enable
      value: false
    - name: administrator
      value: satellite@example.com
