---
- name: Publish Content
  hosts: satellite
  environment:
    SATELLITE_USERNAME: "{{ satellite_username }}"
    SATELLITE_PASSWORD: "{{ satellite_password }}"
    SATELLITE_SERVER_URL: "{{ satellite_server_url }}"
    SATELLITE_VALIDATE_CERTS: "{{ satellite_validate_certs | bool }}"
  tasks:
    - name: "Publish cv-rhel-7"
      redhat.satellite.content_view_version:
        content_view: cv-rhel-7
        organization: "{{ satellite_organization }}"
        version: '1.0'
    - name: "Publish ccv-rhel-7"
      redhat.satellite.content_view_version:
        content_view: ccv-rhel-7
        organization: "{{ satellite_organization }}"
        version: '1.0'
        lifecycle_environments:
          - generic-dev
