---
- name: Satellite Settings
  hosts: satellite
  environment:
    SATELLITE_USERNAME: "{{ satellite_username }}"
    SATELLITE_PASSWORD: "{{ satellite_password }}"
    SATELLITE_SERVER_URL: "{{ satellite_server_url }}"
    SATELLITE_VALIDATE_CERTS: "{{ satellite_validate_certs | bool }}"
  tasks:
    - name: Satellite Locations
      ansible.builtin.include_role:
        name: redhat.satellite.locations
      when: satellite_locations is defined
    - name: Proxy Configuration
      ansible.builtin.include_role:
        name: http_proxies
      when: satellite_http_proxies is defined
    - name: Configure Satellite Settings
      ansible.builtin.include_role:
        name: redhat.satellite.settings
      when: satellite_settings is defined
    - name: Content
      ansible.legacy.include_tasks: tasks/content.yml
