---
- name: Satellite Settings
  hosts: satellite
  collections:
    - redhat.satellite
  environment:
    SATELLITE_USERNAME: "{{ satellite_username }}"
    SATELLITE_PASSWORD: "{{ satellite_password }}"
    SATELLITE_SERVER_URL: "{{ server_url }}"
    SATELLITE_VALIDATE_CERTS: false
  tasks:
    - name: Satellite Locations
      include_tasks: tasks/locations.yml
    - name: Proxy Configuration
      include_tasks: tasks/proxy.yml
    - name: Configure Satellite Settings
      include_role:
        name: redhat.satellite.settings
      when: satellite_settings is defined
    - name: Content
      include_tasks: tasks/content.yml
