---
- name: Satellite Settings
  hosts: localhost
  collections:
    - redhat.satellite
  environment:
    SATELLITE_USERNAME: "{{ satellite_username }}"
    SATELLITE_PASSWORD: "{{ satellite_password }}"
    SATELLITE_SERVER_URL: "{{ server_url }}"
    SATELLITE_VALIDATE_CERTS: false
  tasks:
    - name: Satellite Settings
      include_tasks: tasks/settings.yml
    - name: Satellite Locations
      include_tasks: tasks/locations.yml
    - name: Content
      include_tasks: tasks/content.yml
