---
- name: Satellite Settings
  hosts: satellite
  environment:
    SATELLITE_USERNAME: "{{ satellite_username }}"
    SATELLITE_PASSWORD: "{{ satellite_password }}"
    SATELLITE_SERVER_URL: "{{ satellite_server_url }}"
    SATELLITE_VALIDATE_CERTS: "{{ satellite_validate_certs | bool }}"
  gather_facts: false
  tasks:
    - name: General Configuration (locations, proxy, settings)
      ansible.builtin.include_tasks: tasks/config.yml
    - name: Content
      ansible.builtin.include_tasks: tasks/content.yml
