---
satellite_username: user
# update with `ansible-vault encrypt_string --ask-vault-pass --name satellite_password`
satellite_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      31626231333264613462666135666434383632383037616433653366623634653330636661666563
      6363323131643038316563386466386564363439343736320a333731623161313364393064383435
      33636666626631333232353665373166333836616532663436613761303034666630633133356230
      6234303331366166660a626563636436336233636132623138646537333263386435303538363033
      3832
server_url: https://satellite
satellite_organization: Puzzle ITC
satellite_settings:
  - name: default_redhat_download_policy
    value: immediate
  - name: default_proxy_download_policy
    value: immediate
  - name: rss_enable
    value: false
  - name: administrator
    value: satellite@example.com
satellite_products:
  - name: Red Hat Enterprise Linux for x86_64
    repository_sets:
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
        releasever: 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (Kickstart)
        releasever: 9.1
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
        releasever: 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (Kickstart)
        releasever: 9.1
satellite_sync_plans:
  - name: sync Red Hat content
    interval: daily
    sync_date: 2023-07-17 00:08:15 UTC
    products:
      - Red Hat Enterprise Linux for x86_64
satellite_content_views:
  - name: RHEL 9 Linux all
    repositories:
      - name: Red Hat Enterprise Linux 9 for x86_64 BaseOS RPMs
        product: Red Hat Enterprise Linux for x86_64
      - name: Red Hat Enterprise Linux 9 for x86_64 BaseOS Kickstart
        product: Red Hat Enterprise Linux for x86_64
      - name: Red Hat Enterprise Linux 9 for x86_64 AppStream RPMs
        product: Red Hat Enterprise Linux for x86_64
      - name: Red Hat Enterprise Linux 9 for x86_64 AppStream Kickstart
        product: Red Hat Enterprise Linux for x86_64
  - name: CCV RHEL 9
    components:
      - content_view: RHEL 9 Linux all
        latest: true
